services:
  work-logger:
    image: work-logger
    container_name: work-logger-container
    build:
      context: .
      dockerfile: Work-logger/Dockerfile
    ports:
      - "8888:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w_0Rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Work-logger.pfx
    env_file:
      - .env
    networks:
      - kodzuverse

networks:
  kodzuverse:
    name: kodzuverse_network
    driver: bridge
    external: true

  worklogger.api:
    image: worklogger.api
    build:
      context: .
      dockerfile: WorkLogger.Api/Dockerfile
